from enum import Enum, IntFlag

import pyv4l2.uapi as uapi

__all__ = [ 'MediaEntityFunction', 'MediaLinkFlag', 'MediaPadFlag', 'MediaInterfaceType' ]

class MediaEntityFunction(Enum):
    UNKNOWN = uapi.MEDIA_ENT_F_UNKNOWN
    V4L2_SUBDEV_UNKNOWN = uapi.MEDIA_ENT_F_V4L2_SUBDEV_UNKNOWN
    DTV_DEMOD = uapi.MEDIA_ENT_F_DTV_DEMOD
    TS_DEMUX = uapi.MEDIA_ENT_F_TS_DEMUX
    DTV_CA = uapi.MEDIA_ENT_F_DTV_CA
    DTV_NET_DECAP = uapi.MEDIA_ENT_F_DTV_NET_DECAP
    IO_V4L = uapi.MEDIA_ENT_F_IO_V4L
    IO_DTV = uapi.MEDIA_ENT_F_IO_DTV
    IO_VBI = uapi.MEDIA_ENT_F_IO_VBI
    IO_SWRADIO = uapi.MEDIA_ENT_F_IO_SWRADIO
    CAM_SENSOR = uapi.MEDIA_ENT_F_CAM_SENSOR
    FLASH = uapi.MEDIA_ENT_F_FLASH
    LENS = uapi.MEDIA_ENT_F_LENS
    TUNER = uapi.MEDIA_ENT_F_TUNER
    IF_VID_DECODER = uapi.MEDIA_ENT_F_IF_VID_DECODER
    IF_AUD_DECODER = uapi.MEDIA_ENT_F_IF_AUD_DECODER
    AUDIO_CAPTURE = uapi.MEDIA_ENT_F_AUDIO_CAPTURE
    AUDIO_PLAYBACK = uapi.MEDIA_ENT_F_AUDIO_PLAYBACK
    AUDIO_MIXER = uapi.MEDIA_ENT_F_AUDIO_MIXER
    PROC_VIDEO_COMPOSER = uapi.MEDIA_ENT_F_PROC_VIDEO_COMPOSER
    PROC_VIDEO_PIXEL_FORMATTER = uapi.MEDIA_ENT_F_PROC_VIDEO_PIXEL_FORMATTER
    PROC_VIDEO_PIXEL_ENC_CONV = uapi.MEDIA_ENT_F_PROC_VIDEO_PIXEL_ENC_CONV
    PROC_VIDEO_LUT = uapi.MEDIA_ENT_F_PROC_VIDEO_LUT
    PROC_VIDEO_SCALER = uapi.MEDIA_ENT_F_PROC_VIDEO_SCALER
    PROC_VIDEO_STATISTICS = uapi.MEDIA_ENT_F_PROC_VIDEO_STATISTICS
    PROC_VIDEO_ENCODER = uapi.MEDIA_ENT_F_PROC_VIDEO_ENCODER
    PROC_VIDEO_DECODER = uapi.MEDIA_ENT_F_PROC_VIDEO_DECODER
    PROC_VIDEO_ISP = uapi.MEDIA_ENT_F_PROC_VIDEO_ISP
    VID_MUX = uapi.MEDIA_ENT_F_VID_MUX
    VID_IF_BRIDGE = uapi.MEDIA_ENT_F_VID_IF_BRIDGE
    ATV_DECODER = uapi.MEDIA_ENT_F_ATV_DECODER
    DV_DECODER = uapi.MEDIA_ENT_F_DV_DECODER
    DV_ENCODER = uapi.MEDIA_ENT_F_DV_ENCODER

class MediaLinkFlag(IntFlag):
    ENABLED = uapi.MEDIA_LNK_FL_ENABLED
    IMMUTABLE = uapi.MEDIA_LNK_FL_IMMUTABLE
    DYNAMIC = uapi.MEDIA_LNK_FL_DYNAMIC

class MediaPadFlag(IntFlag):
    SINK = uapi.MEDIA_PAD_FL_SINK
    SOURCE = uapi.MEDIA_PAD_FL_SOURCE
    MUST_CONNECT = uapi.MEDIA_PAD_FL_MUST_CONNECT
    INTERNAL = uapi.MEDIA_PAD_FL_INTERNAL

class MediaInterfaceType(Enum):
    DVB_FE = uapi.MEDIA_INTF_T_DVB_FE
    DVB_DEMUX = uapi.MEDIA_INTF_T_DVB_DEMUX
    DVB_DVR = uapi.MEDIA_INTF_T_DVB_DVR
    DVB_CA = uapi.MEDIA_INTF_T_DVB_CA
    DVB_NET = uapi.MEDIA_INTF_T_DVB_NET
    V4L_VIDEO = uapi.MEDIA_INTF_T_V4L_VIDEO
    V4L_VBI = uapi.MEDIA_INTF_T_V4L_VBI
    V4L_RADIO = uapi.MEDIA_INTF_T_V4L_RADIO
    V4L_SUBDEV = uapi.MEDIA_INTF_T_V4L_SUBDEV
    V4L_SWRADIO = uapi.MEDIA_INTF_T_V4L_SWRADIO
    V4L_TOUCH = uapi.MEDIA_INTF_T_V4L_TOUCH
    ALSA_BASE = uapi.MEDIA_INTF_T_ALSA_BASE
    ALSA_PCM_CAPTURE = uapi.MEDIA_INTF_T_ALSA_PCM_CAPTURE
    ALSA_PCM_PLAYBACK = uapi.MEDIA_INTF_T_ALSA_PCM_PLAYBACK
    ALSA_CONTROL = uapi.MEDIA_INTF_T_ALSA_CONTROL
